<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoEvents\Module'                              => __DIR__ . '/Module.php',
    'UthandoEvents\Form\EventsForm'                     => __DIR__ . '/src/UthandoEvents/Form/EventsForm.php',
    'UthandoEvents\Form\SettingsForm'                   => __DIR__ . '/src/UthandoEvents/Form/SettingsForm.php',
    'UthandoEvents\Hydrator\EventsHydrator'             => __DIR__ . '/src/UthandoEvents/Hydrator/EventsHydrator.php',
    'UthandoEvents\InputFilter\EventsInputFilter'       => __DIR__ . '/src/UthandoEvents/InputFilter/EventsInputFilter.php',
    'UthandoEvents\InputFilter\SettingsInputFilter'     => __DIR__ . '/src/UthandoEvents/InputFilter/SettingsInputFilter.php',
    'UthandoEvents\Mapper\EventsMapper'                 => __DIR__ . '/src/UthandoEvents/Mapper/EventsMapper.php',
    'UthandoEvents\Model\EventModel'                    => __DIR__ . '/src/UthandoEvents/Model/EventModel.php',
    'UthandoEvents\Mvc\Controller\EventsController'     => __DIR__ . '/src/UthandoEvents/Mvc/Controller/EventsController.php',
    'UthandoEvents\Mvc\Controller\SettingsController'   => __DIR__ . '/src/UthandoEvents/Mvc/Controller/SettingsController.php',
    'UthandoEvents\Mvc\Controller\TimeLineController'   => __DIR__ . '/src/UthandoEvents/Mvc/Controller/TimeLineController.php',
    'UthandoEvents\Options\EventsOptions'               => __DIR__ . '/src/UthandoEvents/Options/EventsOptions.php',
    'UthandoEvents\ServiceManager\EventsOptionsFactory' => __DIR__ . '/src/UthandoEvents/ServiceManager/EventsOptionsFactory.php',
    'UthandoEvents\ServiceManager\EventsService'        => __DIR__ . '/src/UthandoEvents/ServiceManager/EventsService.php',
    'UthandoEvents\View\Helper\ConvertDateFormat'       => __DIR__ . '/src/UthandoEvents/View/Helper/ConvertDateFormat.php',
);
