<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-events/events/add'      => __DIR__ . '/view/uthando-events/events/add.phtml',
    'uthando-events/events/edit'     => __DIR__ . '/view/uthando-events/events/edit.phtml',
    'uthando-events/events/index'    => __DIR__ . '/view/uthando-events/events/index.phtml',
    'uthando-events/events/list'     => __DIR__ . '/view/uthando-events/events/list.phtml',
    'uthando-events/time-line/index' => __DIR__ . '/view/uthando-events/time-line/index.phtml',
);
