<?php $this->headTitle('Edit Event') ?>
<?php $this->layout()->pageTitle = 'Edit Event'; ?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
    'form' 			=> $this->form,
    'formName'		=> 'Event',
    'postUrl'		=> $this->url('admin/events/edit', [
        'id'    => $this->model->getEventId(),
    ]),
    'cancelUrl'     => $this->url('admin/events'),
    'formElements'	=> [
        'eventId', 'title', 'dateTime', 'description', 'html',
    ],
]); ?>

<?=$this->partial('uthando-admin/partial/tiny-mce');?>

<script type="text/javascript">
    $(document).ready(function() {
        $('.date-time-pick .input-group').datetimepicker({
            format: '<?=$this->convertDateFormat('js');?>'
        });
    });
</script>
