<?php $this->HeadTitle('Events List'); ?>
<?php $this->layout()->pageTitle = 'Events List'; ?>

<?=$this->partial('uthando-admin/partial/search', [
    'name'			=> 'events',
    'searchInputs'	=> [
        'Events' => 'title-description',
    ],
]);?>


<div id="table-events">
    <?=$this->partial('uthando-events/events/list', [
        'models' => $this->models
    ]); ?>
</div>


<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
    $('#table-events').dataGrid({
        url : 'events/list',
        query: { sort : 'eventId' },
        searchForm : $('#search-events'),
        paging : 'links',
        columnSort: true,
        //rowClick : admin.product.rowClick
    });
});
<?php $this->inlineScript()->captureEnd(); ?>
