
<?php if (count($this->models) > 0): ?>
    <div class="panel panel-default">
        <table id="events-list" class="table table-hover table-bordered table-condensed sortable-table">
            <thead>
            <tr>
                <th data-field="eventsId">Id</th>
                <th data-field="titel">Title</th>
                <th data-field="description">Description</th>
                <th data-field="dateTime">Date/Time</th>
                <th>Actions</th>
            </tr>
            </thead>

            <tbody>
            <?php /* @var $row \UthandoEvents\Model\EventModel */ ?>
            <?php foreach($this->models as $row): ?>
                <tr>
                    <td><?=$this->escapeHtml($row->getEventId()); ?></td>
                    <td><?=$this->escapeHtml($row->getTitle()); ?></td>
                    <td><?=$this->escapeHtml($row->getDescription()); ?></td>
                    <td><?=$this->escapeHtml($row->getDateTime()->format('d/m/Y H:i A')); ?></td>
                    <td>
                        <?=$this->partial('uthando-admin/partial/edit-actions', [
                            'pk'		=> 'eventId',
                            'id'		=> $row->getEventId(),
                            'tableName'	=> 'envents',
                            'route'		=> 'admin/events/edit',
                        ]);?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?=$this->paginationControl(
        $this->models,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'admin/events/page']
    ); ?>

<?php else: ?>
    <h4>No Events where returned by search.</h4>
<?php endif; ?>